### ISSUE TITLE
Menu sidebar tidak tertutup saat menu lainnya di expand

### ISSUE THREAD

**Issue by ashtav** [willymiiee/twin-web#3]
saat menu di sidebar di klik khususnya yang multileple menu, multileple menu lainnya yang diexpand tidak tertutup secara otomatis. Dan saat page tertentu aktif atau diakses, menu sidebar yang berhubungan dengan page tersebut tidak aktif.

**Comment by willymiiee** [comment]
@ashta94 updated the styles for sidebar, it should be fixed.
